DI-4831 - Custom Query templates for analyze tables
udemy/soda-sql pull request #1
Opened 2021-04-05 09:53 UTC by vtascioglu

2021-04-05 12:13 UTC, itasyurt commented on sodasql/dataset_analyzer.py
> +                if table_name in analyze_templates or table_name.upper() in analyze_templates:
@vtascioglu   would it make sense if we traverse  `analyze_templates` once and change keys to lower, so we don't think about upper/lowercase anymore

2021-04-05 12:15 UTC, itasyurt commented on sodasql/dataset_analyzer.py
> +                if table_name in analyze_templates or table_name.upper() in analyze_templates:
@vtascioglu  would it be better if we extract body of the forloop to a function  tha gets column_name and  source_type as parameter

2021-04-05 12:17 UTC, itasyurt commented on sodasql/dataset_analyzer.py
> +                    f'FROM ({analyze_dataset_query}) T'
@vtascioglu  out of curiosity, is the 3.6+ style of  string formatting a prefered way?
(I am new to this, that's why I am asking)

2021-04-05 12:18 UTC, itasyurt commented on sodasql/dialects/athena_dialect.py
> +    def default_analyze_templates(self, params: dict):
@vtascioglu  do we need to unify different default_analyze_templates methods in different dialects?

2021-04-05 12:21 UTC, itasyurt approved these changes
some comments most of them questions, feel free to skip; except these 
- I think it'd be better to extract body  of for loop  in analyze to  a private method
- making the dict keys lowercase by default and do not case about  cases afterwards
o/w lgtm, thanks

2021-04-05 12:33 UTC, vtascioglu commented on sodasql/dataset_analyzer.py
> +                    f'FROM ({analyze_dataset_query}) T'
@itasyurt I think that part needs refactoring a bit but in this particular task i didnt want to try to fix anything extra.

2021-04-05 12:41 UTC, vtascioglu commented on sodasql/dialects/athena_dialect.py
> +    def default_analyze_templates(self, params: dict):
@itasyurt sql server uses top not limit so I have to do that way. I dont know if any other requires some special scripts but if needed just enough to modify the dialect

2021-04-05 12:42 UTC, vtascioglu commented on sodasql/dataset_analyzer.py
> +                if table_name in analyze_templates or table_name.upper() in analyze_templates:
@itasyurt i didnt want to touch other parts of code just concantrated on solving the problem for this time

2021-04-05 13:12 UTC, vtascioglu commented on sodasql/dataset_analyzer.py
> +                if table_name in analyze_templates or table_name.upper() in analyze_templates:
@itasyurt changed it to case sensitive. Also change default keyword to _default, in case of default can be used as table name.

2021-04-05 14:36 UTC, itasyurt commented on sodasql/dialects/sqlserver_dialect.py
> +        params.setdefault('_default','select top 1000 #column_name# from #table_name#')
@vtascioglu  _default should be extracted to a constant imo

2021-04-05 14:37 UTC, itasyurt commented on sodasql/dataset_analyzer.py
> +                    analyze_template = analyze_templates.get(table_name)
analyze_templates[table_name] might be more pythonic

2021-04-05 14:38 UTC, itasyurt commented on sodasql/dataset_analyzer.py
> +                    analyze_template = analyze_templates.get(table_name)
or  analyze_templates.get(table_name, analyze_template_default) can do it in one line

2021-04-05 15:56 UTC, vtascioglu commented on sodasql/dialects/sqlserver_dialect.py
> +        params.setdefault('_default','select top 1000 #column_name# from #table_name#')
done

2021-04-05 15:57 UTC, vtascioglu commented on sodasql/dataset_analyzer.py
> +                    analyze_template = analyze_templates.get(table_name)
changed to more pythonic way

2021-04-05 16:23 UTC, mmigdiso requested changes

2021-04-05 16:23 UTC, mmigdiso commented on sodasql/cli/cli.py
> +@click.option('-a', '--analyze_templates', required=False, default=None, help='Column analyze sql templates')
the help statement is a bit confusing. Can we change it to a better self explanatory statement?

2021-04-05 16:23 UTC, mmigdiso commented on sodasql/cli/cli.py
> +
I'm not sure but json does not seem to be in the requirements.in file. The project uses yml for the config files, can we go with yml here too? 
Can you give an example of analyze_templates json file? what does it contain?

2021-04-05 16:23 UTC, mmigdiso commented on sodasql/dialects/bigquery_dialect.py
> +
should go to the dialect.py and only overridden in the subclass if the templates differs.

2021-04-05 16:23 UTC, mmigdiso commented on sodasql/dialects/hive_dialect.py
> +
should go to the dialect.py and only overridden in the subclass if the templates differs.

2021-04-05 16:23 UTC, mmigdiso commented on sodasql/dialects/postgres_dialect.py
> +
should go to the dialect.py and only overridden in the subclass if the templates differs.

2021-04-05 16:23 UTC, mmigdiso commented on sodasql/dialects/redshift_dialect.py
> +
should go to the dialect.py and only overridden in the subclass if the templates differs.

2021-04-05 16:23 UTC, mmigdiso commented on sodasql/dialects/snowflake_dialect.py
> +
should go to the dialect.py and only overridden in the subclass if the templates differs.

2021-04-05 17:14 UTC, itasyurt submitted a review, later dismissed
lgtm on the  prev. issues I commented for

2021-04-05 17:37 UTC, vtascioglu commented on sodasql/cli/cli.py
> +
@mmigdiso actually its not json file. It will be sent as a parameter for create command. 

    def run_cli_create(self):
        runner = CliRunner()
        result = runner.invoke(main, [
            'create',
            '-d', 'sodasql',
            '-u', 'sodasql',
            '-p', 'sodasql',
            '-w', 'local_postgres_tutorial', 'postgres',
            '-a', '{"_default":"select #column_name# from #table_name# limit 1000",'
                  '"demodata":"select #column_name# from #table_name# where COUNTRY=\'US\' limit 10",'
                  '"test_table":"select #column_name# from #table_name# limit 5"}'
        ])

2021-04-05 17:38 UTC, vtascioglu commented on sodasql/cli/cli.py
> +@click.option('-a', '--analyze_templates', required=False, default=None, help='Column analyze sql templates')
How about this? 

@click.option('-a', '--analyze_templates', required=False, default=None, help='Managed to customize the sql select statements used for column analyze. Default is select column from table limit 1000 or equivalent')

2021-04-05 17:40 UTC, vtascioglu commented on sodasql/dialects/bigquery_dialect.py
> +
done

2021-04-05 17:40 UTC, vtascioglu commented on sodasql/dialects/hive_dialect.py
> +
done

2021-04-05 17:41 UTC, vtascioglu commented on sodasql/dialects/redshift_dialect.py
> +
done

2021-04-05 17:41 UTC, vtascioglu commented on sodasql/dialects/snowflake_dialect.py
> +
done

2021-04-05 21:48 UTC, mmigdiso commented on sodasql/cli/cli.py
> +
cool!

2021-04-05 21:50 UTC, mmigdiso commented on sodasql/cli/cli.py
> +@click.option('-a', '--analyze_templates', required=False, default=None, help='Column analyze sql templates')
If we follow the description of the other parameters as an example, I would propose :
"The dictionary that contains the sql query templates to be used in analyze"

2021-04-05 21:54 UTC, mmigdiso requested changes

2021-04-05 21:54 UTC, mmigdiso commented on sodasql/dialects/snowflake_dialect.py
> +
I don't think that this is needed. It will call the base class if you don't override it.

2021-04-05 21:54 UTC, mmigdiso commented on sodasql/dialects/redshift_dialect.py
> +
I don't think that this is needed. It will call the base class if you don't override it.

2021-04-05 21:54 UTC, mmigdiso commented on sodasql/dialects/postgres_dialect.py
> +
I don't think that this is needed. It will call the base class if you don't override it.

2021-04-05 21:54 UTC, mmigdiso commented on sodasql/dialects/hive_dialect.py
> +
I don't think that this is needed. It will call the base class if you don't override it.

2021-04-05 21:54 UTC, mmigdiso commented on sodasql/dialects/bigquery_dialect.py
> +
I don't think that this is needed. It will call the base class if you don't override it.

2021-04-05 21:54 UTC, mmigdiso commented on sodasql/dialects/athena_dialect.py
> +
I don't think that this is needed. It will call the base class if you don't override it.

2021-04-06 06:48 UTC, mmigdiso requested changes

2021-04-06 06:48 UTC, mmigdiso commented on sodasql/cli/cli.py
> +@click.option('-a', '--analyze_templates', required=False, default=None, help='The dictionary that contains the sql query templatesf for tables to be used to analyze columns')
nit - small typo: templatesf =>templates

2021-04-06 06:50 UTC, vtascioglu commented on sodasql/cli/cli.py
> +@click.option('-a', '--analyze_templates', required=False, default=None, help='The dictionary that contains the sql query templatesf for tables to be used to analyze columns')
done

2021-04-06 08:44 UTC, mmigdiso approved these changes

2021-04-06 09:33 UTC, merged